services:
  mysql:
    container_name: dbrpg-manager
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - rpg-manager-network
  phpmyadmin:
    container_name: phprpg-manager
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - rpg-manager-network
  backend:
    container_name: backend_rpg-manager
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - VERSION=v1
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - rpg-manager-network
  frontend:
    container_name: frontend_rpg-manager
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VERSION=v1
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
      - /app/.next
    networks:
      - rpg-manager-network
networks:
  rpg-manager-network:
    driver: bridge
volumes:
  mysql_data:
  mysql_config:
